### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by runvnc** [maitrix-org/Pandora#6]
Congratulations on this, it looks like an amazing technical achievement. Can you provide a LICENSE file? Also, if you decide not to allow commercial use of the source or weights, please consider providing an API service. This seems like such a powerful concept.

**Comment by guangyliu** [comment]
Thanks for your interest. The current issue is not on our side but on the datasets' side since some datasets are not allowed to share the model weights trained by their data. We're still working on it.

**Comment by szxiangjn** [comment]
Unfortunately, we are not able to release the weights due to data license issues. However, we are training a model with larger-scale data without license issue now, and we will release the model when it is ready.
